language: cpp
dist: bionic
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get -qq install libdlib-dev
- sudo apt-get -qq install libopenblas-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T DlibClustering-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulismut:$BINTRAY_API_KEY "https://api.bintray.com/content/lismut/otus16/otus16/$TRAVIS_BUILD_NUMBER/DlibClustering-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
